project:
  type: website

website:
  title: "Internet Access"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - model.qmd
      - about.qmd
      - sources.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

    