---
title: ""
format: html
execute: 
  echo: false
---

```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(tidymodels))
library(marginaleffects)
library(dplyr)
library(gt)
library(ggplot2)
library(scales)
library(patchwork)
library(stringr)
suppressPackageStartupMessages(library(plotly))
library(scales)
```

These plots highlight the individual impacts of age and household income on Americans' access to internet: people with full access to internet are typically younger and wealthier than those without it. 






```{r}
x <- readRDS("data/x.rds")

#clean data
x <- x |> filter(!is.na(accessinet), !is.na(agep), !is.na(rac1p), !is.na(schl), !is.na(esr), !is.na(hincp), hincp > 0, hincp < 1e6)

x<- x|>
  mutate(accessinet_binary = case_when(
    accessinet == 1 ~ 1,
    accessinet %in% c(2, 3) ~ 0,
    TRUE ~ NA_real_  
  ))

x <- x |>
  mutate(accessinet_binary = factor(accessinet_binary, levels = c(0, 1), labels = c("LimitedOrNoAccess", "FullAccess")))
```

```{r}
medians <- x |>
  group_by(accessinet_binary) |>
  summarise(median_age = median(agep, na.rm = TRUE)) |>
  ungroup()
x|> ggplot(aes(y=agep, x=accessinet_binary))+geom_boxplot()+labs(title="Internet Access in US According to Age", subtitle="The median age of Americans with limited or no internet\naccess was significantly higher than that of Americans\nwith full internet access.", x="Type of Internet Access", y="Age") + scale_y_continuous(breaks = seq(0, max(x$agep, na.rm = TRUE), by = 20))+scale_x_discrete(labels = c("No/Limited Access", "Full Access"))+theme_minimal(base_size = 16) + theme(legend.position = "top", plot.title = element_text(face = "bold"), axis.title.y = element_text(margin = margin(r = 10)), axis.title.x = element_text(margin = margin(t = 10))) -> p1

ggplotly(p1, tooltip = "label")
```





```{r}
avg_inc_by_int <- x |>
  group_by(accessinet_binary) |>
  summarize(hincp = mean(hincp, na.rm = TRUE)) |>
  ungroup()
avg_inc_by_int|> ggplot(aes(x=accessinet_binary,y=hincp,text = paste0("Average: $", scales::comma(hincp))))+geom_col(fill = "steelblue")+labs(title="Average Household Income According to\nInternet Access", subtitle="The average household income of Americans with full\ninternet access was much greater than that of Americans\nwith limited or no internet access.", x="Type of Internet Access", y="Household Income")+scale_x_discrete(labels = c("No/Limited Access", "Full Access"))+scale_y_continuous(breaks = seq(0, max(avg_inc_by_int$hincp, na.rm = TRUE), by = 20000), labels = label_dollar())+theme_minimal(base_size = 16) + theme(legend.position = "top", plot.title = element_text(face = "bold"), axis.title.y = element_text(margin = margin(r = 10)), axis.title.x = element_text(margin = margin(t = 10)))->p2

ggplotly(p2, tooltip = "text")
```
